<?php

/*
 | !!!! DO NOT EDIT THIS FILE !!!!
 |
 | You can change settings by setting them in the environment or .env
 | If there is something you need to change, but is not available as an environment setting,
 | request an environment variable to be created upstream or send a pull request.
 */

use Illuminate\Support\Facades\Facade;

return [

    'timezone' => ini_get('date.timezone') ?: 'UTC', // use existing timezone

    'default_locale' => env('APP_LOCALE', 'en'), // just a holder for the system set locale

    'aliases' => Facade::defaultAliases()->merge([
        'DeviceCache' => App\Facades\DeviceCache::class,
        'Permissions' => App\Facades\Permissions::class,
        'PortCache' => App\Facades\PortCache::class,
        'PluginManager' => App\Facades\PluginManager::class,
        'Rrd' => App\Facades\Rrd::class,
        'SnmpQuery' => App\Facades\FacadeAccessorSnmp::class,
        'twentyfouronlineConfig' => App\Facades\twentyfouronlineConfig::class,
    ])->forget([
        'Http', // don't use Laravel Http facade, twentyfouronline has its own wrapper
    ])->toArray(),

    'charset' => env('CHARSET', ini_get('php.output_encoding') ?: ini_get('default_charset') ?: 'UTF-8'),

    'name' => 'twentyfouronline',
   

    
    'providers' => [

        /*
        |--------------------------------------------------------------------------
        | Laravel Framework Service Providers...
        |--------------------------------------------------------------------------
        */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
        |--------------------------------------------------------------------------
        | Application Service Providers...
        |--------------------------------------------------------------------------
        */
        App\Providers\AppServiceProvider::class,
        // App\Providers\AuthServiceProvider::class,
        // App\Providers\EventServiceProvider::class,
        // App\Providers\RouteServiceProvider::class,
    ],
];

    





